"""bandera check_external_links en scopes

Revision ID: 33f06118e608
Revises: 8fc66d0f1f03
Create Date: 2026-09-03 20:20:55.480685+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "33f06118e608"
down_revision: str | None = "8fc66d0f1f03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scopes",
        sa.Column(
            "check_external_links", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scopes", "check_external_links")
    # ### end Alembic commands ###
