"""columna discovered_from en pages

Revision ID: 8fc66d0f1f03
Revises: d04876272559
Create Date: 2026-09-03 19:13:35.008866+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8fc66d0f1f03"
down_revision: str | None = "d04876272559"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pages", sa.Column("discovered_from", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pages", "discovered_from")
    # ### end Alembic commands ###
