"""esquema inicial del dominio

Revision ID: d04876272559
Revises:
Create Date: 2026-09-03 16:46:30.036858+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d04876272559"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "projects",
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("client_name", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_projects_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("owner_id", "name", name=op.f("uq_projects_owner_id_name")),
    )
    op.create_index(op.f("ix_projects_owner_id"), "projects", ["owner_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.UUID(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["refresh_tokens.id"],
            name=op.f("fk_refresh_tokens_replaced_by_id_refresh_tokens"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
    )
    op.create_index(
        op.f("ix_refresh_tokens_expires_at"), "refresh_tokens", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "search_console_connections",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("google_account_email", sa.Text(), nullable=True),
        sa.Column("property_url", sa.Text(), nullable=True),
        sa.Column("refresh_token_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("scopes", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "connected",
                "revoked",
                "error",
                name="connection_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="connected",
            nullable=False,
        ),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_search_console_connections_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_console_connections")),
        sa.UniqueConstraint("project_id", name=op.f("uq_search_console_connections_project_id")),
    )
    op.create_table(
        "sites",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column("authorized_by", sa.Text(), nullable=True),
        sa.Column("authorization_date", sa.Date(), nullable=True),
        sa.Column("authorization_notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("base_url ~* '^https?://'", name=op.f("ck_sites_base_url_scheme")),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_sites_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sites")),
        sa.UniqueConstraint("project_id", "base_url", name=op.f("uq_sites_project_id_base_url")),
    )
    op.create_index(op.f("ix_sites_project_id"), "sites", ["project_id"], unique=False)
    op.create_table(
        "scans",
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("triggered_by", sa.UUID(), nullable=True),
        sa.Column(
            "scan_type",
            sa.Enum(
                "full",
                "security",
                "seo",
                "performance",
                name="scan_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "completed",
                "failed",
                "cancelled",
                "partial",
                name="scan_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column(
            "queued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("scope_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("engine_version", sa.Text(), nullable=False),
        sa.Column("app_version", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("progress BETWEEN 0 AND 100", name=op.f("ck_scans_progress_range")),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_scans_site_id_sites"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by"],
            ["users.id"],
            name=op.f("fk_scans_triggered_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scans")),
    )
    op.create_index("ix_scans_site_id_queued_at", "scans", ["site_id", "queued_at"], unique=False)
    op.create_index(op.f("ix_scans_status"), "scans", ["status"], unique=False)
    op.create_table(
        "scopes",
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("allowed_domains", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "allowed_paths", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "excluded_paths", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("max_pages", sa.Integer(), server_default="200", nullable=False),
        sa.Column("max_depth", sa.Integer(), server_default="3", nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), server_default="20", nullable=False),
        sa.Column("request_delay_ms", sa.Integer(), server_default="200", nullable=False),
        sa.Column("concurrency", sa.Integer(), server_default="4", nullable=False),
        sa.Column("respect_robots", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "zap_spider_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("auth_profile_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cardinality(allowed_domains) > 0", name=op.f("ck_scopes_allowed_domains_present")
        ),
        sa.CheckConstraint(
            "concurrency BETWEEN 1 AND 16", name=op.f("ck_scopes_concurrency_range")
        ),
        sa.CheckConstraint("max_depth BETWEEN 1 AND 10", name=op.f("ck_scopes_max_depth_range")),
        sa.CheckConstraint("max_pages BETWEEN 1 AND 5000", name=op.f("ck_scopes_max_pages_range")),
        sa.CheckConstraint(
            "request_delay_ms BETWEEN 0 AND 10000", name=op.f("ck_scopes_delay_range")
        ),
        sa.CheckConstraint(
            "timeout_seconds BETWEEN 1 AND 120", name=op.f("ck_scopes_timeout_range")
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_scopes_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scopes")),
        sa.UniqueConstraint("site_id", name=op.f("uq_scopes_site_id")),
    )
    op.create_table(
        "findings",
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "zap",
                "seo",
                "crawler",
                "pagespeed",
                "search_console",
                name="finding_source",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "security",
                "seo",
                "performance",
                "accessibility",
                "best_practices",
                name="finding_category",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("rule_id", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "critical",
                "high",
                "medium",
                "low",
                "info",
                name="finding_severity",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "confidence",
            sa.Enum(
                "high",
                "medium",
                "low",
                name="finding_confidence",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("parameter", sa.Text(), nullable=True),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("impact", sa.Text(), nullable=True),
        sa.Column("remediation", sa.Text(), nullable=True),
        sa.Column("client_explanation", sa.Text(), nullable=True),
        sa.Column("cwe", sa.Text(), nullable=True),
        sa.Column("owasp", sa.Text(), nullable=True),
        sa.Column(
            "references",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("occurrences", sa.Integer(), server_default="1", nullable=False),
        sa.Column("fingerprint", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "fixed",
                "accepted",
                "false_positive",
                name="finding_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="open",
            nullable=False,
        ),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("occurrences >= 1", name=op.f("ck_findings_occurrences_positive")),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], name=op.f("fk_findings_scan_id_scans"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
        sa.UniqueConstraint("scan_id", "fingerprint", name=op.f("uq_findings_scan_id_fingerprint")),
    )
    op.create_index("ix_findings_fingerprint", "findings", ["fingerprint"], unique=False)
    op.create_index(
        "ix_findings_scan_id_severity", "findings", ["scan_id", "severity"], unique=False
    )
    op.create_index("ix_findings_scan_id_source", "findings", ["scan_id", "source"], unique=False)
    op.create_table(
        "pages",
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("url_hash", sa.LargeBinary(), nullable=False),
        sa.Column("depth", sa.SmallInteger(), nullable=False),
        sa.Column("status_code", sa.SmallInteger(), nullable=True),
        sa.Column("content_type", sa.Text(), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("content_length", sa.Integer(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("meta_description", sa.Text(), nullable=True),
        sa.Column("canonical", sa.Text(), nullable=True),
        sa.Column("meta_robots", sa.Text(), nullable=True),
        sa.Column("h1", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("h2", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("internal_links", sa.Integer(), server_default="0", nullable=False),
        sa.Column("external_links", sa.Integer(), server_default="0", nullable=False),
        sa.Column("images_total", sa.Integer(), server_default="0", nullable=False),
        sa.Column("images_missing_alt", sa.Integer(), server_default="0", nullable=False),
        sa.Column("scripts_total", sa.Integer(), server_default="0", nullable=False),
        sa.Column("forms_total", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "redirect_chain",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "structured_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_indexable", sa.Boolean(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], name=op.f("fk_pages_scan_id_scans"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pages")),
        sa.UniqueConstraint("scan_id", "url_hash", name=op.f("uq_pages_scan_id_url_hash")),
    )
    op.create_index(
        "ix_pages_scan_id_status_code", "pages", ["scan_id", "status_code"], unique=False
    )
    op.create_table(
        "performance_results",
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column(
            "strategy",
            sa.Enum(
                "mobile",
                "desktop",
                name="pagespeed_strategy",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("performance_score", sa.SmallInteger(), nullable=True),
        sa.Column("accessibility_score", sa.SmallInteger(), nullable=True),
        sa.Column("best_practices_score", sa.SmallInteger(), nullable=True),
        sa.Column("seo_score", sa.SmallInteger(), nullable=True),
        sa.Column("lcp_ms", sa.Integer(), nullable=True),
        sa.Column("cls", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("inp_ms", sa.Integer(), nullable=True),
        sa.Column("fcp_ms", sa.Integer(), nullable=True),
        sa.Column("tbt_ms", sa.Integer(), nullable=True),
        sa.Column("speed_index_ms", sa.Integer(), nullable=True),
        sa.Column("lighthouse_version", sa.Text(), nullable=True),
        sa.Column("has_field_data", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "performance_score IS NULL OR performance_score BETWEEN 0 AND 100",
            name=op.f("ck_performance_results_performance_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
            name=op.f("fk_performance_results_scan_id_scans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_performance_results")),
        sa.UniqueConstraint(
            "scan_id", "url", "strategy", name=op.f("uq_performance_results_scan_id_url_strategy")
        ),
    )
    op.create_table(
        "reports",
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column(
            "format",
            sa.Enum(
                "pdf",
                "html",
                "json",
                name="report_format",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("report_version", sa.Text(), nullable=False),
        sa.Column(
            "audience",
            sa.Enum(
                "technical",
                "executive",
                "combined",
                name="report_audience",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="combined",
            nullable=False,
        ),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("checksum_sha256", sa.Text(), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], name=op.f("fk_reports_scan_id_scans"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        sa.UniqueConstraint(
            "scan_id",
            "format",
            "audience",
            "report_version",
            name=op.f("uq_reports_scan_id_format_audience_report_version"),
        ),
    )
    op.create_table(
        "scan_modules",
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column(
            "module",
            sa.Enum(
                "discovery",
                "crawler",
                "security",
                "seo",
                "performance",
                "search_console",
                "findings",
                "scoring",
                "report",
                name="module_name",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                "skipped",
                name="module_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
            name=op.f("fk_scan_modules_scan_id_scans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_modules")),
        sa.UniqueConstraint("scan_id", "module", name=op.f("uq_scan_modules_scan_id_module")),
    )
    op.create_table(
        "scores",
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column(
            "system",
            sa.Enum(
                "softree", "google", name="score_system", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "overall",
                "security",
                "performance",
                "seo",
                "accessibility",
                "best_practices",
                name="score_category",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("weight", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("engine_version", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "value IS NULL OR value BETWEEN 0 AND 100", name=op.f("ck_scores_value_range")
        ),
        sa.CheckConstraint(
            "weight IS NULL OR weight BETWEEN 0 AND 1", name=op.f("ck_scores_weight_range")
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], name=op.f("fk_scores_scan_id_scans"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scores")),
        sa.UniqueConstraint(
            "scan_id", "system", "category", name=op.f("uq_scores_scan_id_system_category")
        ),
    )
    op.create_table(
        "search_console_metrics",
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column(
            "period",
            sa.Enum(
                "7d",
                "28d",
                "90d",
                name="search_console_period",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "dimension",
            sa.Enum(
                "date",
                "query",
                "page",
                "country",
                "device",
                name="search_console_dimension",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("dimension_value", sa.Text(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("ctr", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("position", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
            name=op.f("fk_search_console_metrics_scan_id_scans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_console_metrics")),
        sa.UniqueConstraint(
            "scan_id",
            "period",
            "dimension",
            "dimension_value",
            name=op.f("uq_search_console_metrics_scan_id_period_dimension_dimension_value"),
        ),
    )
    op.create_index(
        "ix_search_console_metrics_scan_period_dim",
        "search_console_metrics",
        ["scan_id", "period", "dimension"],
        unique=False,
    )
    op.create_table(
        "seo_results",
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("pages_crawled", sa.Integer(), server_default="0", nullable=False),
        sa.Column("urls_discovered", sa.Integer(), server_default="0", nullable=False),
        sa.Column("missing_title", sa.Integer(), server_default="0", nullable=False),
        sa.Column("duplicate_title", sa.Integer(), server_default="0", nullable=False),
        sa.Column("missing_description", sa.Integer(), server_default="0", nullable=False),
        sa.Column("duplicate_description", sa.Integer(), server_default="0", nullable=False),
        sa.Column("missing_h1", sa.Integer(), server_default="0", nullable=False),
        sa.Column("multiple_h1", sa.Integer(), server_default="0", nullable=False),
        sa.Column("images_missing_alt", sa.Integer(), server_default="0", nullable=False),
        sa.Column("broken_internal_links", sa.Integer(), server_default="0", nullable=False),
        sa.Column("broken_external_links", sa.Integer(), server_default="0", nullable=False),
        sa.Column("missing_canonical", sa.Integer(), server_default="0", nullable=False),
        sa.Column("noindex_pages", sa.Integer(), server_default="0", nullable=False),
        sa.Column("redirect_chains", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "robots_txt_found", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("sitemap_found", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("sitemap_urls", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "structured_data_summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], name=op.f("fk_seo_results_scan_id_scans"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seo_results")),
        sa.UniqueConstraint("scan_id", name=op.f("uq_seo_results_scan_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("seo_results")
    op.drop_index("ix_search_console_metrics_scan_period_dim", table_name="search_console_metrics")
    op.drop_table("search_console_metrics")
    op.drop_table("scores")
    op.drop_table("scan_modules")
    op.drop_table("reports")
    op.drop_table("performance_results")
    op.drop_index("ix_pages_scan_id_status_code", table_name="pages")
    op.drop_table("pages")
    op.drop_index("ix_findings_scan_id_source", table_name="findings")
    op.drop_index("ix_findings_scan_id_severity", table_name="findings")
    op.drop_index("ix_findings_fingerprint", table_name="findings")
    op.drop_table("findings")
    op.drop_table("scopes")
    op.drop_index(op.f("ix_scans_status"), table_name="scans")
    op.drop_index("ix_scans_site_id_queued_at", table_name="scans")
    op.drop_table("scans")
    op.drop_index(op.f("ix_sites_project_id"), table_name="sites")
    op.drop_table("sites")
    op.drop_table("search_console_connections")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_expires_at"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_projects_owner_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_table("users")
    # ### end Alembic commands ###
